version: '3.4'

services:
  db_pmr_dev:
    image: mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pmrdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  
  backend_dev:
    build:
      context: BackendPMRApp
      dockerfile: dev.dockerfile
    working_dir: /usr/src/backend
    volumes:
      - ./BackendPMRApp/:/usr/src/backend
    ports:
      - '8080:8080'
    expose:
      - '8080'
    command: mvn spring-boot:run
    links:
      - db_pmr_dev:mariadb
  fronted_dev:
    build:
      context: Fronted
      dockerfile: ionic.dockerfile
    working_dir: /usr/src/fronted
    volumes:
      - ./Fronted/:/usr/src/fronted
      - /usr/src/fronted/node_modules
    command: /bin/sh ionic.sh
      